name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 requests
        pip install -t package bs4 requests

    - name: Package the code
      run: |
        cp api/main.py package/
        cd package
        zip -r9 ../lambda_function.zip .

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        function-name: ga-incarceration-status
        zip-file: lambda_function.zip
        handler: main.handler
